### ISSUE TITLE
error: can't copy 'tensorflow/compiler/xla/python_api/xla_shape.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by Saarraaaah** [nathtest/Tutorial-Ubuntu-18.04-Install-Nvidia-driver-and-CUDA-and-CUDNN-and-build-Tensorflow-for-gpu#1]
I am getting this error in the last step 

Please help!

**Comment by nathtest** [comment]
It's certainly a little too late to respond. Since I didn't get any notification that an issue was open.
I cannot replicate your problem, but it does seem recurrent.
Here some links to the official tensorflow githut issues, addressing the same error:
https://github.com/tensorflow/tensorflow/issues/1594
https://github.com/tensorflow/tensorflow/issues/9035
https://github.com/tensorflow/tensorflow/issues/8078
